
#GET http://localhost:5082/tasks



# POST  http://localhost:5082/tasks
# Content-Type: application/json

# {
#     "Title" : "Сходить в магмзин",
#     "Description" : "Купить по списку:..."
# }

#GET http://localhost:5082/tasks/2